Data handling restructure
ChEB-AI/python-chebai pull request #29
Opened 2024-05-27 20:53 UTC by aditya0by0

- PR for Issue #10  

# Goal
- Have 3 preprocessing stages:
  - first stages only contains `chebi.obo` (raw)
  - second stage contains data _without_ split, but with labels attached (processed 1)
  - third level contains _encoded_ data (again without split) (processed 2)
- Splits are created "on the fly" 
  - Test that they can be reproduced with some seed (compare hashes)
- The file structure should represent this:
  - Current file paths are `data/ChEBIX/chebi_version/raw` / `data/ChEBIX/chebi_version/processed/encoding`
  - Instead, only take the parameters that are important for each step:
  - raw: `data/chebi_version/raw`
  - processed 1: `data/chebi_version/ChEBIX/processed`
  - processed 2: `data/chebi_version/ChEBIX/processed/encoding`

2024-05-28 18:47 UTC, sfluegel05 requested changes
Thanks for the implementation. To me, this is looking good and working as intended.

I only have two change requests:
- Could you also update the tests for chebi (`testChebiData`)? I would assume sume of them don't work anymore since there are no `test.pt` files anymore.
- For the seed: The cleanest way would be to embed it into the lightning config system. You wrote a custom parsing function. You could have saved yourself the effort by adding the seed as an init parameter to the class. Then, a user can add a seed to their regular data config file. And if not, some default value is used instead of raising an error. Could you do that instead?

2024-05-30 08:35 UTC, sfluegel05 commented
Some additional changes we talked about:
- tests: 
  - instantiate data class directly instead of loading it from a config file, 
  - automatically create data if it not already present
- store created datasplits in variables to avoid recreating them 
- overload `load_processed_data` instead of `dataloader` to avoid code duplication
- check if the evaluation in `tutorials/eval_model_basic.ipnb` still works, update if necessary

2024-06-11 09:01 UTC, aditya0by0 commented
Hi @sfluegel05, Please review the PR. 
I request for bit more time to look into `tutorials/eval_model_basic.ipynb` due to some unrelated errors.

2024-06-12 14:22 UTC, aditya0by0 commented
> Hi @sfluegel05, Please review the PR. I request for bit more time to look into `tutorials/eval_model_basic.ipynb` due to some errors.

Hi @sfluegel05, I have made the changes for  `tutorials/eval_model_basic.ipynb` and to other relevant `.py` files related to it.
Please review the PR.

2024-06-13 15:43 UTC, sfluegel05 reviewed
The remaining change requests for this PR from my side:
- for a class with `chebi_version` != `train_version`, instead of creating additional `v_{train_version}` files, refer to the same files that would be used by a class that has the `train_version` as its main version (e.g. instead of creating two files `chebi.obo` and `chebi_v200.obo` in `chebi_v231/raw`, create `chebi_v200/raw/chebi.obo` and `chebi_v231/raw/chebi.obo`
- remove commented out cells from notebook

2024-06-13 15:43 UTC, sfluegel05 commented on chebai/preprocessing/datasets/chebi.py
> +    def load_processed_data(self, kind: str = None) -> List:
here, you should add a `filename` parameter that allows the user to load an arbitrary file (independent of splits).

2024-06-19 21:44 UTC, aditya0by0 commented
Also, I have updated the wiki `Data-Management/Data folder structure` for the new folder structure according to this PR.
Please review.

2024-06-23 15:14 UTC, aditya0by0 commented
Also, can you please confirm whether merging this PR will lead to closure of the below issue too
- #12

2024-06-24 08:19 UTC, sfluegel05 approved these changes
This looks good. Thanks for implementing.
Regarding issue #12, I'd say this solves this first part (reproducing data splits), but not the second one (reproducing runs).

2024-06-24 16:35 UTC, aditya0by0 commented
Hi @sfluegel05, as you have approved the changes. Can you please merge the PR if there are no further actions/changes left for this issue.

2024-06-26 12:59 UTC, sfluegel05 commented
I will merge this PR, but before that, I have another task. Since this change will require other users of this tool to change their datasets, it would be useful to have a migration script. I created an issue for that: #34

2024-07-05 11:49 UTC, merged